# Generated by Django 5.2.6 on 2025-09-30 00:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['roll_number'],
                'indexes': [models.Index(fields=['roll_number'], name='students_st_roll_nu_6ff92b_idx'), models.Index(fields=['class_name'], name='students_st_class_n_f8fef9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('subjects', models.JSONField(help_text="Array of subjects with name and max_marks. Example: [{'name': 'Math', 'max_marks': 100}]")),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='students_te_date_6af3c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('marks_obtained', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.test')),
            ],
            options={
                'ordering': ['-test__date', 'student__roll_number'],
                'indexes': [models.Index(fields=['student', 'test'], name='students_ma_student_5fbd4d_idx'), models.Index(fields=['test'], name='students_ma_test_id_ce8a9d_idx')],
                'unique_together': {('student', 'test', 'subject_name')},
            },
        ),
    ]
